"""remove external external_img_url field

Revision ID: 2e22a0ef7b35
Revises: 55efec04d81b
Create Date: 2026-03-15 18:14:19.057876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e22a0ef7b35'
down_revision: Union[str, Sequence[str], None] = '55efec04d81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'external_img_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('external_img_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
