"""add external hero fields

Revision ID: 55efec04d81b
Revises: 65a6d6786f3e
Create Date: 2026-03-03 00:22:21.074998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55efec04d81b'
down_revision: Union[str, Sequence[str], None] = '65a6d6786f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('external_id', sa.Integer(), nullable=True))
    op.add_column('heroes', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('heroes', sa.Column('publisher', sa.String(length=100), nullable=True))
    op.add_column('heroes', sa.Column('external_img_url', sa.Text(), nullable=True))
    op.add_column('heroes', sa.Column('uploaded_img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'uploaded_img_url')
    op.drop_column('heroes', 'external_img_url')
    op.drop_column('heroes', 'publisher')
    op.drop_column('heroes', 'full_name')
    op.drop_column('heroes', 'external_id')
    # ### end Alembic commands ###
