"""add_unique_constraint_to_hero_name

Revision ID: 65a6d6786f3e
Revises: 8ef3ae83dd1e
Create Date: 2026-02-20 00:33:27.243289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a6d6786f3e'
down_revision: Union[str, Sequence[str], None] = '8ef3ae83dd1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroes_name'), table_name='heroes')
    op.create_unique_constraint('uq_hero_name', 'heroes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_hero_name', 'heroes', type_='unique')
    op.create_index(op.f('ix_heroes_name'), 'heroes', ['name'], unique=False)
    # ### end Alembic commands ###
