"""Fixed updated_at field for Base model

Revision ID: 8ef3ae83dd1e
Revises: ffa0c5a5f341
Create Date: 2026-01-13 00:01:37.308349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef3ae83dd1e'
down_revision: Union[str, Sequence[str], None] = 'ffa0c5a5f341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
