"""Fixed updated_at field for Base model

Revision ID: 8ef3ae83dd1e
Revises: ffa0c5a5f341
Create Date: 2026-01-13 00:01:37.308349

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8ef3ae83dd1e"
down_revision: str | Sequence[str] | None = "ffa0c5a5f341"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
